### Adding Column to a Data Frame

In [1]:
import numpy as np  
import pandas as pd

In [2]:
data = {'Name': ['Jane', 'Princi', 'James', 'Fadi'],
        'Height': [5.1, 6.2, 5.1, 5.2],
        'Qualification': ['Msc', 'MA', 'Msc', 'Msc'],
        'Score 1' : [56,86,77,45],
        'Score 2' : [50,96,60,30]}

df = pd.DataFrame(data)

In [3]:
print('Data Frame Before New Column:')
df.head()

Data Frame Before New Column:

     Name  Height Qualification  Score 1  Score 2
0    Jane     5.1           Msc       56       50
1  Princi     6.2            MA       86       96
2   James     5.1           Msc       77       60
3    Fadi     5.2           Msc       45       30

In [9]:
addreess = ['NYC', 'NJ', 'CA', 'PA']

df('Address') == address

TypeError: 'DataFrame' object is not callable

In [10]:
print('Before Column Add:')
df.head()

Before Column Add:

     Name  Height Qualification  Score 1  Score 2
0    Jane     5.1           Msc       56       50
1  Princi     6.2            MA       86       96
2   James     5.1           Msc       77       60
3    Fadi     5.2           Msc       45       30

In [12]:
#ADD COLUMN using old column
df['Total Score'] = df['score 1'] + df['score 2']

print('After Column Add:')
df.head()

KeyError: 'score 1'

In [11]:
df['Avg_Score'] = df['Total']/2
df.head()

KeyError: 'Total'

### IMPORTING SPECIFIED and rEARRANGING THEM

In [6]:
data = {'Name': ['Jane', 'Princi', 'James', 'Fadi'],
        'Height': [5.1, 6.2, 5.1, 5.2],
        'Qualification': ['Msc', 'MA', 'Msc', 'Msc'],
        'Score 1' : [56,86,77,45],
        'Score 2' : [50,96,60,30]}

df2 = pd.DataFrame(data, columns=['Score 1', 'Score 2','Name', 'Qualification'])
print(df2)

   Score 1  Score 2    Name Qualification
0       56       50    Jane           Msc
1       86       96  Princi            MA
2       77       60   James           Msc
3       45       30    Fadi           Msc

In [5]:
values = [['Rohan', 455], ['Elvish', 250], ['John', 495],
          ['Sai', 400], ['Eric', 350], ['Adam', 450]]

df3 = pd.DataFrame(values, columns=['Name', 'Univ_Marks'])

df3.head()

     Name  Univ_Marks
0   Rohan         455
1  Elvish         250
2    John         495
3     Sai         400
4    Eric         350

In [ ]:
df['Percentage'] = (df['Univ_Marks'] / 500) * 100

KeyError: 'Univ_Marks'

### Using the  . insert() method to add a column

In [ ]:
# UAsing insert allows you to get more central of where column is inserted
df3.insert(1, 'Age',[1000, 2000, 50, 60, 12, 13])

df3.head()

NameError: name 'df3' is not defined

In [ ]:
df3 = df3.assign(location=['MiddleEarth', 'Georgia', 'NYC', 'CA', 'MA'])
df3.head()