# CREATING A PANDAS DataFrame

In [1]:
import numpy as np
import pandas as pd

In [2]:
d = {'x': [1, 2, 3], 'y': [2, 4, 8], 'z': 100}

df = pd.DataFrame(d)

In [3]:
df2 = pd.DataFrame(d, index=[100, 200, 300], columns=['z', 'y', 'x'])

In [4]:
student_dict = {
    'Name': ['Joe', 'Nat', 'Harry'],
    'Age': [20, 21, 19],
    'Marks': [85.10, 77.80, 91.54]
}

student_df = pd.DataFrame(student_dict)
student_df.head()

    Name  Age  Marks
0    Joe   20  85.10
1    Nat   21  77.80
2  Harry   19  91.54

In [5]:
student_df.dtypes

Name         str
Age        int64
Marks    float64
dtype: object

In [6]:
data = {
    'Product': ['Laptop', 'Tablet', 'Phone'],
    'Price': [1200, 300, 800],
    'Quantity': [50, 150, 100]
}

df3 = pd.DataFrame(data)
df3.head()

  Product  Price  Quantity
0  Laptop   1200        50
1  Tablet    300       150
2   Phone    800       100

In [11]:
df3.index = pd.RangeIndex(start=1, stop=4, step=1)

df3.head()

  Product  Price  Quantity
1  Laptop   1200        50
2  Tablet    300       150
3   Phone    800       100

In [13]:
# create a list of patientID, name, and date of birth and assign it to a variable
patientID = [101,23,48,49]
name =       ['alice','bob','charlie','Eric']
# create a list of dates
date_of_birth = ['2023-01-01', '2023-01-02', '3/10/2020 143045', '13th of October, 2023']

# WHen using zip to create a DF, you should provide column names
employee_df = pd.DataFrame(zip(patientID, name, date_of_birth), columns=['patientID', 'name', 'dob'])

employee_df.head()

   patientID     name                    dob
0        101    alice             2023-01-01
1         23      bob             2023-01-02
2         48  charlie       3/10/2020 143045
3         49     Eric  13th of October, 2023

In [14]:
# in this example, we create a list of stocks and their prices and then create a DataFrame.
stocks = ["IBM", "APPLE", "TWTTR", "GE", "MSFT"]
prices = [115.00, 119.14, 19.77, 25.99, 26]

# Take these lists, make a data frame with column names: stock, price
stock_df = pd.DataFrame(zip(stocks, prices), columns=['Stock', 'Price'])

stock_df.head()

   Stock   Price
0    IBM  115.00
1  APPLE  119.14
2  TWTTR   19.77
3     GE   25.99
4   MSFT   26.00

In [15]:
arr = np.array([[1, 2, 100], [2, 4, 100], [3, 8, 100]])

numpy_df = pd.DataFrame(arr, columns=['x','y', 'z'])

numpy_df.head()

   x  y    z
0  1  2  100
1  2  4  100
2  3  8  100