# Pandas Basic

pandas is a wrapper of 2 language
 . Numpy - numerical data and mathimatical operation
 . matplotlib

In [1]:
import numpy as numpy
import pandas as pd

In [2]:
print(f'pandas: {pd.__version__}')
print(f'numpy: {pd.__version__}')

pandas: 3.0.2
numpy: 3.0.2

panda datastructure
. Serious - single Dimensional data structure
          -homogeneous
.Dataframe - multidimentional table
     Hetrogeneous

In [3]:
ser1 = pd.Series([10, 20, 30,40], index=["A", "B", "C", "D"])
print(ser1)

A    10
B    20
C    30
D    40
dtype: int64

In [4]:
calories = { 
    'day1': 700, 
    'day2': 2500, 
    'day3': 1200
}

ser4 = pd.Series(calories, index=['day1', 'day3'])

print(ser4)

day1     700
day3    1200
dtype: int64

In [5]:
ser5 = pd.Series(5.0, index= [ "a","b", "c"])

print(ser5)

a    5.0
b    5.0
c    5.0
dtype: float64

In [6]:
import pandas as pd

fruit_data = {
    'apple_sales': [3, 2, 0, 2, 9, 4, 7, 2],
    'orange_sales': [0, 3, 2, 7, 7, 8, 3, 0]
}

# Fix 1: RangeIndex only needs start and stop (and optionally step)
# This creates an index from 2000 to 2007
idx = pd.RangeIndex(start=2000, stop=2008)

# Fix 2: Use the 'idx' variable you just created for the DataFrame index
purchases = pd.DataFrame(fruit_data, index=idx)

print(purchases)

      apple_sales  orange_sales
2000            3             0
2001            2             3
2002            0             2
2003            2             7
2004            9             7
2005            4             8
2006            7             3
2007            2             0

In [7]:
rows,cols=purchases.shape
print(f'Rows:{rows}')
print(f'cals:{rows}')

Rows:8
cals:8

In [8]:
print(purchases.head())

      apple_sales  orange_sales
2000            3             0
2001            2             3
2002            0             2
2003            2             7
2004            9             7

In [9]:
print(purchases.tail())

      apple_sales  orange_sales
2003            2             7
2004            9             7
2005            4             8
2006            7             3
2007            2             0

In [ ]:
import pandas as pd 

# Step 1: Add the full relative path
employee_df = pd.read_csv('pandasLesson_data/data/employee.csv')

# Step 2: Run the cell
employee_df.head()

      Name   Age  Weight     Salary
0    James  36.0    75.0  5428000.0
1  Villers  38.0    74.0  3428000.0
2    VKole  31.0    70.0  8428000.0
3    Smith  34.0    80.0  4428000.0
4    Gayle  40.0   100.0  4528000.0

In [ ]:
rows, cols = employee_df.shape
print('Rows')

- Date Profiling
      - sstructure(shape)
      - Quality(missing values, duplicat, unique values )
      - content (data types,dispersion,measure centeal tendency)
- profiling Tehciciqs
    - Data Type and Formate Validation
    - Statistical Summaries
    - uniqeness and cardinality
    - Patern Recoginition
    - Cross Validation

In [ ]:
cars_df = pd.read_json('pandasLesson_data/data/cars.json')

cars_df.head()

,Car,MPG,Cylinders,Displacement,Horsepower,Weight,Acceleration,Model,Origin,quantity,city
0,Chevrolet Vega,25.0,4,140.0,75,2542,17.0,74,US,177,NJ
1,Chevrolet Vega (sw),22.0,4,140.0,72,2408,19.0,71,US,91,DALLAS
2,Chevrolet Vega 2300,28.0,4,140.0,90,2264,15.5,71,US,74,TEXAS
3,Chevrolet Woody,24.5,4,98.0,60,2164,22.1,76,US,241,OH
4,Chevrolete Chevelle Malibu,16.0,6,250.0,105,3897,18.5,75,US,206,NewYork

In [ ]:
rwos, cols = cars_df.shape

print('Rows: rows')
print('Cals: cals')

Rows: rows
Cals: cals

In [ ]:
cars_df.dtypes

Car                 str
MPG             float64
Cylinders         int64
Displacement    float64
Horsepower        int64
Weight            int64
Acceleration    float64
Model             int64
Origin              str
quantity          int64
city                str
dtype: object

In [ ]:
#Getting a brief overview of descriptive stastics(quantitative data)
cars_df.describe()

,MPG,Cylinders,Displacement,Horsepower,Weight,Acceleration,Model,quantity
count,161.000000,161.000000,161.000000,161.000000,161.000000,161.000000,161.000000,161.000000
mean,23.801863,5.347826,185.232919,100.664596,2915.093168,15.509938,76.260870,224.875776
std,8.810125,1.761607,105.394809,41.079640,890.293883,2.515780,3.818576,127.741084
min,0.000000,3.000000,68.000000,0.000000,1613.000000,8.000000,70.000000,5.000000
25%,17.000000,4.000000,98.000000,72.000000,2130.000000,14.000000,73.000000,112.000000
50%,24.000000,4.000000,140.000000,88.000000,2625.000000,15.500000,76.000000,227.000000
75%,31.000000,8.000000,302.000000,130.000000,3620.000000,17.100000,80.000000,337.000000
max,46.600000,8.000000,440.000000,215.000000,4955.000000,22.100000,82.000000,439.000000

In [ ]:
cars_df['city'].value_counts()

city
NewYork    36
NJ         35
DALLAS     33
TEXAS      30
OH         27
Name: count, dtype: int64

In [ ]:
cars_df['city'].unique()

<StringArray>
['NJ', 'DALLAS', 'TEXAS', 'OH', 'NewYork']
Length: 5, dtype: str

In [ ]:
cars_df.info()

<class 'pandas.DataFrame'>
RangeIndex: 161 entries, 0 to 160
Data columns (total 11 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Car           161 non-null    str
 1   MPG           161 non-null    float64
 2   Cylinders     161 non-null    int64
 3   Displacement  161 non-null    float64
 4   Horsepower    161 non-null    int64
 5   Weight        161 non-null    int64
 6   Acceleration  161 non-null    float64
 7   Model         161 non-null    int64
 8   Origin        161 non-null    str
 9   quantity      161 non-null    int64
 10  city          161 non-null    str
dtypes: float64(3), int64(5), str(3)
memory usage: 14.0 KB

In [ ]:
cars_df.count()

Car             161
MPG             161
Cylinders       161
Displacement    161
Horsepower      161
Weight          161
Acceleration    161
Model           161
Origin          161
quantity        161
city            161
dtype: int64

In [ ]:
cars_df.head(2)

,Car,MPG,Cylinders,Displacement,Horsepower,Weight,Acceleration,Model,Origin,quantity,city
0,Chevrolet Vega,25.0,4,140.0,75,2542,17.0,74,US,177,NJ
1,Chevrolet Vega (sw),22.0,4,140.0,72,2408,19.0,71,US,91,DALLAS

In [ ]:
cars_df.tail(2)

,Car,MPG,Cylinders,Displacement,Horsepower,Weight,Acceleration,Model,Origin,quantity,city
159,Mercury Lynx l,36.0,4,98.0,70,2125,17.3,82,US,425,TEXAS
160,Mercury Marquis,11.0,8,429.0,208,4633,11.0,72,US,112,OH

In [ ]:
# .at method
cars_df.at[159,"MPG"]

np.float64(36.0)

In [ ]:
cars_df.iloc[159]

Car             Mercury Lynx l
MPG                       36.0
Cylinders                    4
Displacement              98.0
Horsepower                  70
Weight                    2125
Acceleration              17.3
Model                       82
Origin                      US
quantity                   425
city                     TEXAS
Name: 159, dtype: object

In [ ]:
cars_df.iat[159,1]

np.float64(36.0)

In [ ]:
student_dict = {'Name': ['Joe', 'Nat', 'Harry'], 'Age': [20, 21, 19], 'Marks': [85.10, 77.80, 91.54]}

student_df = pd.DataFrame(student_dict)

In [ ]:
print(student_df.describe())

        Age      Marks
count   3.0   3.000000
mean   20.0  84.813333
std     1.0   6.874484
min    19.0  77.800000
25%    19.5  81.450000
50%    20.0  85.100000
75%    20.5  88.320000
max    21.0  91.540000

In [ ]:
import pandas as pd

student_dict = {'Name': ['Joe', 'Nat', 'Harry'], 'Age': [20, 21, 19], 'Marks': [85.10, 77.80, 91.54]}
student_df = pd.DataFrame(student_dict)

# use the DataFrame
print(student_df.describe())

list_index = student_df.columns
print('Columns names', list_index)

        Age      Marks
count   3.0   3.000000
mean   20.0  84.813333
std     1.0   6.874484
min    19.0  77.800000
25%    19.5  81.450000
50%    20.0  85.100000
75%    20.5  88.320000
max    21.0  91.540000
Columns names Index(['Name', 'Age', 'Marks'], dtype='str')

In [ ]:
list_Index = student_df.columns
print('Columns Names', list_Index)

Columns Names Index(['Name', 'Age', 'Marks'], dtype='str')

In [ ]:
label = student_df.columns[0]
print(label)

Name

In [ ]:
lables_as_list = student_df

#EDA w/CSV

In [ ]:
e_df = pd.read_csv('pandasLesson_data/data/employee.csv')

In [ ]:
e_df.head()

      Name   Age  Weight     Salary
0    James  36.0    75.0  5428000.0
1  Villers  38.0    74.0  3428000.0
2    VKole  31.0    70.0  8428000.0
3    Smith  34.0    80.0  4428000.0
4    Gayle  40.0   100.0  4528000.0

In [ ]:
e_df.tail()

     Name   Age  Weight     Salary
10  Jenny   NaN   100.0    25632.0
11   Kenn   NaN   110.0    25632.0
12    Aly   NaN    90.0    25582.0
13   John  41.0    85.0  1528000.0
14    Ali  26.0    69.0        NaN

In [ ]:
e_df.info(2)

<class 'pandas.DataFrame'>
RangeIndex: 15 entries, 0 to 14
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Name    14 non-null     str
 1   Age     12 non-null     float64
 2   Weight  14 non-null     float64
 3   Salary  12 non-null     float64
dtypes: float64(3), str(1)
memory usage: 612.0 bytes

In [ ]:
e_df2 = pd.read_csv('pandasLesson_data/data/employee.csv', skiprows=5, header=None)

e_df2

           0     1      2          3
0      Gayle  40.0  100.0  4528000.0
1       Adam  40.0    NaN  4528000.0
2     Rooter  33.0   72.0  7028000.0
3   Peterson  42.0   85.0  2528000.0
4      lynda  42.0   85.0        NaN
5        NaN  42.0   85.0        NaN
6      Jenny   NaN  100.0    25632.0
7       Kenn   NaN  110.0    25632.0
8        Aly   NaN   90.0    25582.0
9       John  41.0   85.0  1528000.0
10       Ali  26.0   69.0        NaN

In [ ]:
e_df3 = pd.read_csv('pandasLesson_data/data/employee.csv', usecols=[0,3])

e_df3

        Name     Salary
0      James  5428000.0
1    Villers  3428000.0
2      VKole  8428000.0
3      Smith  4428000.0
4      Gayle  4528000.0
5       Adam  4528000.0
6     Rooter  7028000.0
7   Peterson  2528000.0
8      lynda        NaN
9        NaN        NaN
10     Jenny    25632.0
11      Kenn    25632.0
12       Aly    25582.0
13      John  1528000.0
14       Ali        NaN

#SELECTING COLUMNS

In [17]:
df_cars = pd.read_json('pandasLesson_data/data/cars.json')

df_cars.head()

,Car,MPG,Cylinders,Displacement,Horsepower,Weight,Acceleration,Model,Origin,quantity,city
0,Chevrolet Vega,25.0,4,140.0,75,2542,17.0,74,US,177,NJ
1,Chevrolet Vega (sw),22.0,4,140.0,72,2408,19.0,71,US,91,DALLAS
2,Chevrolet Vega 2300,28.0,4,140.0,90,2264,15.5,71,US,74,TEXAS
3,Chevrolet Woody,24.5,4,98.0,60,2164,22.1,76,US,241,OH
4,Chevrolete Chevelle Malibu,16.0,6,250.0,105,3897,18.5,75,US,206,NewYork

In [18]:
#accesing single values, single brackets
df_cars.columns[0]

'Car'

In [19]:
#accesing multiple values, double brackets
df_cars.columns[[0, 1, 2]]

Index(['Car', 'MPG', 'Cylinders'], dtype='str')

In [20]:
#accesing a serious
df_cars['Car']

0                  Chevrolet Vega
1             Chevrolet Vega (sw)
2             Chevrolet Vega 2300
3                 Chevrolet Woody
4      Chevrolete Chevelle Malibu
                  ...
156              Mercury Capri v6
157       Mercury Cougar Brougham
158         Mercury Grand Marquis
159                Mercury Lynx l
160               Mercury Marquis
Name: Car, Length: 161, dtype: str

In [21]:
df_cars[['Car', 'MPG', 'quantity']]

                            Car   MPG  quantity
0                Chevrolet Vega  25.0       177
1           Chevrolet Vega (sw)  22.0        91
2           Chevrolet Vega 2300  28.0        74
3               Chevrolet Woody  24.5       241
4    Chevrolete Chevelle Malibu  16.0       206
..                          ...   ...       ...
156            Mercury Capri v6  21.0       158
157     Mercury Cougar Brougham  15.0        27
158       Mercury Grand Marquis  16.5       332
159              Mercury Lynx l  36.0       425
160             Mercury Marquis  11.0       112

[161 rows x 3 columns]

In [ ]:
df_cars[df_cars.columns[[0, 1, 9]]]

                            Car   MPG  quantity
0                Chevrolet Vega  25.0       177
1           Chevrolet Vega (sw)  22.0        91
2           Chevrolet Vega 2300  28.0        74
3               Chevrolet Woody  24.5       241
4    Chevrolete Chevelle Malibu  16.0       206
..                          ...   ...       ...
156            Mercury Capri v6  21.0       158
157     Mercury Cougar Brougham  15.0        27
158       Mercury Grand Marquis  16.5       332
159              Mercury Lynx l  36.0       425
160             Mercury Marquis  11.0       112

[161 rows x 3 columns]

### Frequency Analysis - Value Counts

In [ ]:
# Sample DataFrame
data = {'Category': ['Electronics', 'Clothing', 'Electronics', 'Books', 'Books', 'Clothing']}

cat_df = pd.DataFrame(data)

cat_df.value_counts()

Category
Electronics    2
Clothing       2
Books          2
Name: count, dtype: int64

In [ ]:
# Create the dataframe
sales_data={"Devices":['Laptop','iPhone','LED','LCD','Smart-Phone','Washing-Machine'],
           'Brand':['Lenovo','Apple','Samsung','Samsung','Samsung','Whirpool'],
           'Sales':[1000,2000,4000,2000,1000,4000],
           'Profit':[500,1000,1000,1500,1000,1500],
           'Pices left':[5000,4000,4000,5000,5000,1000]}

sales_df = pd.DataFrame(sales_data)

Frequency = sales_df['Brand'].value_counts()
print(Frequency)

frequent_product = Frequency[Frequency > 1].index[0]

print(Frequency)

Brand
Samsung     3
Lenovo      1
Apple       1
Whirpool    1
Name: count, dtype: int64
Brand
Samsung     3
Lenovo      1
Apple       1
Whirpool    1
Name: count, dtype: int64

In [ ]:
data = {'Score': [85, 92, 88, 75, None,90, None, 85]}

score_df = pd.DataFrame(data)

In [ ]:
score_counts = score_df.value_counts(dropna=False) #dropna
print('score:', score_counts)

score: Score
85.0     2
NaN      2
92.0     1
88.0     1
75.0     1
90.0     1
Name: count, dtype: int64

Converting  Pandas Column List

### Sorts Using Pandas

In [16]:
import pandas as pd
# Define a dictionary containing Students data
data = {'Name': ['Jane', 'Princi', 'James', 'Fadi'],
        'Height': [5.1, 6.2, 5.1, 5.2],
        'Qualification': ['Msc', 'MA', 'Msc', 'Msc'],
       'Score 1' : [56,86,77,45],
       'Score 2' : [50,96,60,30]}
print("------before -------")
# Convert the dictionary into DataFrame
df = pd.DataFrame(data)
print(df)
print("------after adding column -------")
# using DataFrame.assign() method adding 'Address' column and equating it to the list
df = df.assign(address = ['NYC', 'NJ', 'CA', 'PA'])
print(df)

------before -------
     Name  Height Qualification  Score 1  Score 2
0    Jane     5.1           Msc       56       50
1  Princi     6.2            MA       86       96
2   James     5.1           Msc       77       60
3    Fadi     5.2           Msc       45       30
------after adding column -------
     Name  Height Qualification  Score 1  Score 2 address
0    Jane     5.1           Msc       56       50     NYC
1  Princi     6.2            MA       86       96      NJ
2   James     5.1           Msc       77       60      CA
3    Fadi     5.2           Msc       45       30      PA

In [17]:
print("------after sorting -------")
print(df.sort_values(by='Score 1', ascending=False))

------after sorting -------
     Name  Height Qualification  Score 1  Score 2 address
1  Princi     6.2            MA       86       96      NJ
2   James     5.1           Msc       77       60      CA
0    Jane     5.1           Msc       56       50     NYC
3    Fadi     5.2           Msc       45       30      PA

In [18]:
print (df.sort_values(by=['Score 1', 'Height'], ascending=[False, True]))

     Name  Height Qualification  Score 1  Score 2 address
1  Princi     6.2            MA       86       96      NJ
2   James     5.1           Msc       77       60      CA
0    Jane     5.1           Msc       56       50     NYC
3    Fadi     5.2           Msc       45       30      PA

In [20]:
import pandas as pd
df_cars = pd.read_json('pandasLesson_data\data\cars.json')

print("------before -------")
 df_cars.head(15)

<>:2: SyntaxWarning: "\d" is an invalid escape sequence. Such sequences will not work in the future. Did you mean "\\d"? A raw string is also an option.
<>:2: SyntaxWarning: "\d" is an invalid escape sequence. Such sequences will not work in the future. Did you mean "\\d"? A raw string is also an option.
C:\Users\Tatek\AppData\Local\Temp\ipykernel_21388\1394428964.py:2: SyntaxWarning: "\d" is an invalid escape sequence. Such sequences will not work in the future. Did you mean "\\d"? A raw string is also an option.
  df_cars = pd.read_json('pandasLesson_data\data\cars.json')

IndentationError: unexpected indent (1394428964.py, line 5)

### Slicing a dataframe with .iloc[] and .loc[]

In [8]:
# importing pandas library
import pandas as pd

# Initializing the nested list with Data set
employee_list = [['James', 36, 75, 5428000],
               ['Villers', 38, 74, 3428000],
               ['VKole', 31, 70, 8428000],
               ['Smith', 34, 80, 4428000],
               ['Gayle', 40, 100, 4528000],
               ['Rooter', 33, 72, 7028000],
               ['Peterson', 42, 85, 2528000],
               ['John', 41, 85, 1528000],

]


# creating a pandas dataframe
df = pd.DataFrame(employee_list, columns=['Name', 'Age', 'Weight', 'Salary'])

print(' ------data frame before slicing-----')
print(df)

print(' ------ Select First Row by Index-----')
# Select First Row by Index
print(df.iloc[:1])

print(' ------ Select First 4 Row by Index-----')
# Slicing first 4 rows from dataframe
df1 = df.iloc[0:4]
# This above line used the iloc indexer to slice (select) the first 4 rows of the #original DataFrame (df) and assigns the result to a new DataFrame named df1.

print(' ------data frame after slicing----')
print(df1)

 ------data frame before slicing-----
       Name  Age  Weight   Salary
0     James   36      75  5428000
1   Villers   38      74  3428000
2     VKole   31      70  8428000
3     Smith   34      80  4428000
4     Gayle   40     100  4528000
5    Rooter   33      72  7028000
6  Peterson   42      85  2528000
7      John   41      85  1528000
 ------ Select First Row by Index-----
    Name  Age  Weight   Salary
0  James   36      75  5428000
 ------ Select First 4 Row by Index-----
 ------data frame after slicing----
      Name  Age  Weight   Salary
0    James   36      75  5428000
1  Villers   38      74  3428000
2    VKole   31      70  8428000
3    Smith   34      80  4428000

In [9]:
df.head()

      Name  Age  Weight   Salary
0    James   36      75  5428000
1  Villers   38      74  3428000
2    VKole   31      70  8428000
3    Smith   34      80  4428000
4    Gayle   40     100  4528000

In [10]:
# Initializing the nested list with Data set
employee_list = [['James', 36, 75, 5428000],
               ['Villers', 38, 74, 3428000],
               ['VKole', 31, 70, 8428000],
               ['Smith', 34, 80, 4428000],
               ['Gayle', 40, 100, 4528000],
               ['Rooter', 33, 72, 7028000],
               ['Peterson', 42, 85, 2528000],
               ['John', 41, 85, 1528000]]

# creating a pandas dataframe
df = pd.DataFrame(employee_list, columns=['Name', 'Age', 'Weight', 'Salary'])

# data frame before slicing
print(df)
print( '====Slicing columns in dataframe======')

emp_df =df.iloc[:, 0:2]
print(emp_df)

       Name  Age  Weight   Salary
0     James   36      75  5428000
1   Villers   38      74  3428000
2     VKole   31      70  8428000
3     Smith   34      80  4428000
4     Gayle   40     100  4528000
5    Rooter   33      72  7028000
6  Peterson   42      85  2528000
7      John   41      85  1528000
====Slicing columns in dataframe======
       Name  Age
0     James   36
1   Villers   38
2     VKole   31
3     Smith   34
4     Gayle   40
5    Rooter   33
6  Peterson   42
7      John   41

In [ ]:
#Select values from row index 0 to 2(exclusive) and column position 0 to 2(exclusive)
print(df1.iloc[0:2, 0:2])

      Name  Age
0    James   36
1  Villers   38

In [12]:
import pandas as pd

#create DataFrame with six columns
df = pd.DataFrame({'team': ['A', 'B', 'C', 'D', 'E', 'F', 'G', 'H'],
                   'points': [18, 22, 19, 14, 14, 11, 20, 28],
                   'assists': [5, 7, 7, 9, 12, 9, 9, 4],
                   'rebounds': [11, 8, 10, 6, 6, 5, 9, 12],
                   'steals': [4, 3, 3, 2, 5, 4, 3, 8],
                   'blocks': [1, 0, 0, 3, 2, 2, 1, 5]})

#view DataFrame
print(df)

  team  points  assists  rebounds  steals  blocks
0    A      18        5        11       4       1
1    B      22        7         8       3       0
2    C      19        7        10       3       0
3    D      14        9         6       2       3
4    E      14       12         6       5       2
5    F      11        9         5       4       2
6    G      20        9         9       3       1
7    H      28        4        12       8       5

In [13]:
#slice columns team and rebounds
df_new = df.loc[:, ['team', 'rebounds']]

#view new DataFrame
print(df_new)

  team  rebounds
0    A        11
1    B         8
2    C        10
3    D         6
4    E         6
5    F         5
6    G         9
7    H        12

In [14]:
#slice columns between team and rebounds
df_new = df.loc[:, 'team':'rebounds']

#view new DataFrame
print(df_new)

  team  points  assists  rebounds
0    A      18        5        11
1    B      22        7         8
2    C      19        7        10
3    D      14        9         6
4    E      14       12         6
5    F      11        9         5
6    G      20        9         9
7    H      28        4        12

In [15]:
print(df.loc[3:6, ['team']])

  team
3    D
4    E
5    F
6    G

### Guided Lab 386.3.15 - Generating a date range using date_range() function

In [27]:
import pandas as pd


import pandas as pd
dateRange = pd.date_range(start = "07-01-2023", end = "07-31-2025")
dateRange

dateRange = pd.date_range(start = "07-01-2023", end = "07-31-2025")
dateRange

DatetimeIndex(['2023-07-01', '2023-07-02', '2023-07-03', '2023-07-04',
               '2023-07-05', '2023-07-06', '2023-07-07', '2023-07-08',
               '2023-07-09', '2023-07-10',
               ...
               '2025-07-22', '2025-07-23', '2025-07-24', '2025-07-25',
               '2025-07-26', '2025-07-27', '2025-07-28', '2025-07-29',
               '2025-07-30', '2025-07-31'],
              dtype='datetime64[us]', length=762, freq='D')

In [29]:
datarang_period = pd.date_range(start='01-01-2023', end='07-31-2025', periods=10)
datarang_period

DatetimeIndex(['2023-01-01 00:00:00', '2023-04-15 16:00:00',
               '2023-07-29 08:00:00', '2023-11-11 00:00:00',
               '2024-02-23 16:00:00', '2024-06-07 08:00:00',
               '2024-09-20 00:00:00', '2025-01-02 16:00:00',
               '2025-04-17 08:00:00', '2025-07-31 00:00:00'],
              dtype='datetime64[us]', freq=None)

In [30]:
dateRange = pd.date_range(start = "01-01-2023", end = "07-31-2025", freq ="6T")

dateRange

ValueError: Invalid frequency: 6T. Failed to parse with error message: ValueError("Invalid frequency: T. Failed to parse with error message: KeyError('T'). Did you mean min?")

In [31]:
pd.date_range(start = "01-01-2023", end = "07-31-2025", freq='B')

DatetimeIndex(['2023-01-02', '2023-01-03', '2023-01-04', '2023-01-05',
               '2023-01-06', '2023-01-09', '2023-01-10', '2023-01-11',
               '2023-01-12', '2023-01-13',
               ...
               '2025-07-18', '2025-07-21', '2025-07-22', '2025-07-23',
               '2025-07-24', '2025-07-25', '2025-07-28', '2025-07-29',
               '2025-07-30', '2025-07-31'],
              dtype='datetime64[us]', length=674, freq='B')

In [32]:
pd.date_range(start = "01-01-2023", end = "07-31-2025", freq='W')

DatetimeIndex(['2023-01-01', '2023-01-08', '2023-01-15', '2023-01-22',
               '2023-01-29', '2023-02-05', '2023-02-12', '2023-02-19',
               '2023-02-26', '2023-03-05',
               ...
               '2025-05-25', '2025-06-01', '2025-06-08', '2025-06-15',
               '2025-06-22', '2025-06-29', '2025-07-06', '2025-07-13',
               '2025-07-20', '2025-07-27'],
              dtype='datetime64[us]', length=135, freq='W-SUN')

In [36]:
dateRange = pd.date_range(start ="01-01-2023", periods=6, freq ="2ME")
print(dateRange)

DatetimeIndex(['2023-01-31', '2023-03-31', '2023-05-31', '2023-07-31',
               '2023-09-30', '2023-11-30'],
              dtype='datetime64[us]', freq='2ME')

In [37]:
dateRange = pd.date_range(start ="01-01-2023", periods=6, tz="Asia/Tokyo")
print(dateRange)

DatetimeIndex(['2023-01-01 00:00:00+09:00', '2023-01-02 00:00:00+09:00',
               '2023-01-03 00:00:00+09:00', '2023-01-04 00:00:00+09:00',
               '2023-01-05 00:00:00+09:00', '2023-01-06 00:00:00+09:00'],
              dtype='datetime64[us, Asia/Tokyo]', freq='D')

In [38]:
import pandas as pd
import numpy as np

# Set a specific start date and number of periods (days)
start_date = '2023-01-01'
num_days = 30

# Generate a date range
date_range = pd.date_range(start=start_date, periods=num_days, freq='D')

# Simulate stock prices for each date
np.random.seed(42)
stock_prices = np.random.normal(loc=100, scale=5, size=num_days).round(2)

# Create a DataFrame
stock_df = pd.DataFrame({'Date': date_range, 'StockPrice': stock_prices})

# Display the DataFrame
print(stock_df)

         Date  StockPrice
0  2023-01-01      102.48
1  2023-01-02       99.31
2  2023-01-03      103.24
3  2023-01-04      107.62
4  2023-01-05       98.83
5  2023-01-06       98.83
6  2023-01-07      107.90
7  2023-01-08      103.84
8  2023-01-09       97.65
9  2023-01-10      102.71
10 2023-01-11       97.68
11 2023-01-12       97.67
12 2023-01-13      101.21
13 2023-01-14       90.43
14 2023-01-15       91.38
15 2023-01-16       97.19
16 2023-01-17       94.94
17 2023-01-18      101.57
18 2023-01-19       95.46
19 2023-01-20       92.94
20 2023-01-21      107.33
21 2023-01-22       98.87
22 2023-01-23      100.34
23 2023-01-24       92.88
24 2023-01-25       97.28
25 2023-01-26      100.55
26 2023-01-27       94.25
27 2023-01-28      101.88
28 2023-01-29       97.00
29 2023-01-30       98.54

In [39]:
import pandas as pd
import datetime

# 1. Creating a Timestamp from a string
#    pandas is quite flexible in parsing various string formats.
timestamp_str = pd.Timestamp('2023-01-15 10:30:00')
print(f"Timestamp from string: {timestamp_str}")
print(f"Type of timestamp_str: {type(timestamp_str)}\n")

# 2. Creating a Timestamp from a datetime.datetime object
dt_object = datetime.datetime(2024, 7, 21, 14, 45, 10)
timestamp_dt = pd.Timestamp(dt_object)
print(f"Timestamp from datetime object: {timestamp_dt}")
print(f"Type of timestamp_dt: {type(timestamp_dt)}\n")

Timestamp from string: 2023-01-15 10:30:00
Type of timestamp_str: <class 'pandas.Timestamp'>

Timestamp from datetime object: 2024-07-21 14:45:10
Type of timestamp_dt: <class 'pandas.Timestamp'>

In [40]:
# 3. Creating a Timestamp with specific components (year, month, day, hour, minute, second)
#    You can pass individual components as keyword arguments.
timestamp_components = pd.Timestamp(year=2025, month=3, day=1, hour=9, minute=0, second=0)
print(f"Timestamp from components: {timestamp_components}")
print(f"Type of timestamp_components: {type(timestamp_components)}\n")

# 4. Accessing attributes of a Timestamp object
print(f"Year: {timestamp_components.year}")
print(f"Month: {timestamp_components.month}")
print(f"Day: {timestamp_components.day}")
print(f"Hour: {timestamp_components.hour}")
print(f"Minute: {timestamp_components.minute}")
print(f"Second: {timestamp_components.second}")
print(f"Day of week (0=Monday, 6=Sunday): {timestamp_components.dayofweek}")
print(f"Name of the day: {timestamp_components.day_name()}")
print(f"Is it a leap year?: {timestamp_components.is_leap_year}\n")

# 5. Creating a Timestamp with timezone information
#    Timestamps can also handle timezone awareness.
timestamp_tz = pd.Timestamp('2023-01-15 10:30:00', tz='America/New_York')
print(f"Timestamp with timezone: {timestamp_tz}")
print(f"Timezone: {timestamp_tz.tz}\n")

# 6. Converting a Timestamp to a different timezone
timestamp_tz_utc = timestamp_tz.tz_convert('UTC')
print(f"Timestamp converted to UTC: {timestamp_tz_utc}")

Timestamp from components: 2025-03-01 09:00:00
Type of timestamp_components: <class 'pandas.Timestamp'>

Year: 2025
Month: 3
Day: 1
Hour: 9
Minute: 0
Second: 0
Day of week (0=Monday, 6=Sunday): 5
Name of the day: Saturday
Is it a leap year?: False

Timestamp with timezone: 2023-01-15 10:30:00-05:00
Timezone: America/New_York

Timestamp converted to UTC: 2023-01-15 15:30:00+00:00

In [44]:
url='https://raw.githubusercontent.com/bprasad26/lwd/master/data/tesla_stock_prices.csv'
# using parse_dates to change type from string into date
tesla_df = pd.read_csv(url, parse_dates=['Date'])
# tesla_df.to_csv('data/tesla_stocks.csv')
tesla_df.head()
# tesla_df.info()

        Date       Open   High        Low      Close  Adj Close    Volume
0 2010-06-29  19.000000  25.00  17.540001  23.889999  23.889999  18766300
1 2010-06-30  25.790001  30.42  23.299999  23.830000  23.830000  17187100
2 2010-07-01  25.000000  25.92  20.270000  21.959999  21.959999   8218800
3 2010-07-02  23.000000  23.10  18.709999  19.200001  19.200001   5139800
4 2010-07-06  20.000000  20.00  15.830000  16.110001  16.110001   6866900

In [45]:
# Add new columns to dataframe based off of dates
tesla_df['Day'] = tesla_df['Date'].dt.day
tesla_df['Month'] = tesla_df['Date'].dt.month
tesla_df['Year'] = tesla_df['Date'].dt.year
tesla_df['day_name'] = tesla_df['Date'].dt.day_name()

tesla_df.head(10)

,Date,Open,High,Low,Close,Adj Close,Volume,Day,Month,Year,day_name
0,2010-06-29,19.000000,25.000000,17.540001,23.889999,23.889999,18766300,29,6,2010,Tuesday
1,2010-06-30,25.790001,30.420000,23.299999,23.830000,23.830000,17187100,30,6,2010,Wednesday
2,2010-07-01,25.000000,25.920000,20.270000,21.959999,21.959999,8218800,1,7,2010,Thursday
3,2010-07-02,23.000000,23.100000,18.709999,19.200001,19.200001,5139800,2,7,2010,Friday
4,2010-07-06,20.000000,20.000000,15.830000,16.110001,16.110001,6866900,6,7,2010,Tuesday
5,2010-07-07,16.400000,16.629999,14.980000,15.800000,15.800000,6921700,7,7,2010,Wednesday
6,2010-07-08,16.139999,17.520000,15.570000,17.459999,17.459999,7711400,8,7,2010,Thursday
7,2010-07-09,17.580000,17.900000,16.549999,17.400000,17.400000,4050600,9,7,2010,Friday
8,2010-07-12,17.950001,18.070000,17.000000,17.049999,17.049999,2202500,12,7,2010,Monday
9,2010-07-13,17.389999,18.639999,16.900000,18.139999,18.139999,2680100,13,7,2010,Tuesday

In [49]:
# Step 1: Add the full relative path
df = pd.read_csv('pandasLesson_data/netflix1.csv')

# Step 2: Run the cell
df.head()

,show_id,type,title,director,country,date_added,release_year,rating,duration,listed_in
0,s1,Movie,Dick Johnson Is Dead,Kirsten Johnson,United States,9/25/2021,2020,PG-13,90 min,Documentaries
1,s3,TV Show,Ganglands,Julien Leclercq,France,9/24/2021,2021,TV-MA,1 Season,"Crime TV Shows, International TV Shows, TV Act..."
2,s6,TV Show,Midnight Mass,Mike Flanagan,United States,9/24/2021,2021,TV-MA,1 Season,"TV Dramas, TV Horror, TV Mysteries"
3,s14,Movie,Confessions of an Invisible Girl,Bruno Garotti,Brazil,9/22/2021,2021,TV-PG,91 min,"Children & Family Movies, Comedies"
4,s8,Movie,Sankofa,Haile Gerima,United States,9/24/2021,1993,TV-MA,125 min,"Dramas, Independent Movies, International Movies"

In [50]:
df.tail()

,show_id,type,title,director,country,date_added,release_year,rating,duration,listed_in
8785,s8797,TV Show,Yunus Emre,Not Given,Turkey,1/17/2017,2016,TV-PG,2 Seasons,"International TV Shows, TV Dramas"
8786,s8798,TV Show,Zak Storm,Not Given,United States,9/13/2018,2016,TV-Y7,3 Seasons,Kids' TV
8787,s8801,TV Show,Zindagi Gulzar Hai,Not Given,Pakistan,12/15/2016,2012,TV-PG,1 Season,"International TV Shows, Romantic TV Shows, TV ..."
8788,s8784,TV Show,Yoko,Not Given,Pakistan,6/23/2018,2016,TV-Y,1 Season,Kids' TV
8789,s8786,TV Show,YOM,Not Given,Pakistan,6/7/2018,2016,TV-Y7,1 Season,Kids' TV

In [51]:
df.describe()

       release_year
count   8790.000000
mean    2014.183163
std        8.825466
min     1925.000000
25%     2013.000000
50%     2017.000000
75%     2019.000000
max     2021.000000